### PR TITLE
Added last {target} detection and bounding boxes

### PR DESCRIPTION
**Pull request by ping-localhost**
I saw that you wanted to handle bounding boxes at the platform level, but I decided to create a PR anyway, since I would like to have that feature now (instead of later). 😄 

- Added last {target} detection
- Allow an image to be saved
  - Draws bounding boxes with their label, but only if the confidence is over the confidence passed

I haven't changed any of the tests (or even ran them), since my Python knowledge is very limited, so I do expect them to break/be broken.

### CODE REVIEW

**Comment by robmarkcole** [comment]
Hi thanks for this
You have `from homeassistant.util.pil import draw_box` but then not used from `draw_box` an reimplemented the functionality. Please use `draw_box`. With that change this should be GTG
Thanks

**Comment by ping-localhost** [comment]
Ah, that is correct @robmarkcole. I somehow kept messing up the order the points should be in. I'll look into a bit more.

**Comment by ping-localhost** [comment]
I have tried to use `draw_box`, but I'm getting weird errors I didn't get yesterday. So for now, I've just removed the import. If you could take a look that would be appreciated. I could also add a `TODO` so we can resolve it later on.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 135, in async_update
    await self.async_process_image(image.content)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/amazon_rekognition/image_processing.py", line 174, in process_image
    save_image(image, response, self._target, self._confidence, self._save_file_folder)
  File "/config/custom_components/amazon_rekognition/image_processing.py", line 104, in save_image
    draw_box(draw, area, img_width, img_height, text=box_label)
  File "/usr/src/homeassistant/homeassistant/util/pil.py", line 42, in draw_box
    fill=color,
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageDraw.py", line 158, in line
    self.draw.draw_lines(xy, ink, width)
TypeError: must be real number, not list
```

**Comment by robmarkcole** [comment]
please persist and use `draw_box`. I am happy to help debug the wierd errors

**Comment by ping-localhost** [comment]
I suspect that as well, but as far as I can see (comparing code from others), what I had should have been fine. Anyway, I'll take another look. Are you in the HomeAssistant Discord by any chance?

**Comment by ping-localhost** [comment]
Alright, I've changed the code to `draw_box` for the bounding box (I used `[]` instead of `()`). I decided to not use the `text`-portion of `draw_box`, as that would render it in the same color as the box itself. 

Personally, I think `green` for the box and `white` for the text makes it a lot more readable. If you disagree, I'll change it right away. 😄

**Comment by robmarkcole** [comment]
@ping-localhost could you also update the README with the new config, then its good to go. 
Thanks!

**Comment by ping-localhost** [comment]
Ah yes, of course. Totally forgot!

**Comment by ping-localhost** [comment]
Alright, it should be good to go now @robmarkcole

**Comment by ping-localhost** [comment]
I just noticed an issue with the `save_file_path`. If you have multiple entities, it does not overwrites the image. It should be two separate images though, so let me fix that real quick. 🔧

**Comment by ping-localhost** [comment]
Alright, now it should be good to go @robmarkcole. 😁

**Comment by robmarkcole** [comment]
Thanks for your contribution, great work!

**Pull request merged**
